// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PPAI_2.Infra.Data;

#nullable disable

namespace PPAI2.Migrations
{
    [DbContext(typeof(RedSismicaContext))]
    [Migration("20251106120925_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.29");

            modelBuilder.Entity("PPAI_Revisiones.Modelos.AlcanceSismo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Alcances");
                });

            modelBuilder.Entity("PPAI_Revisiones.Modelos.CambioDeEstado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EventoSismicoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaHoraFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaHoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResponsableId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventoSismicoId");

                    b.HasIndex("ResponsableId");

                    b.ToTable("CambiosDeEstado");
                });

            modelBuilder.Entity("PPAI_Revisiones.Modelos.ClasificacionSismo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("KmProfundidadDesde")
                        .HasColumnType("REAL");

                    b.Property<double>("KmProfundidadHasta")
                        .HasColumnType("REAL");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clasificaciones");
                });

            modelBuilder.Entity("PPAI_Revisiones.Modelos.DetalleMuestra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MuestraSismicaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TipoDeDatoId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MuestraSismicaId");

                    b.HasIndex("TipoDeDatoId");

                    b.ToTable("DetallesMuestra");
                });

            modelBuilder.Entity("PPAI_Revisiones.Modelos.Empleado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellido")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("PPAI_Revisiones.Modelos.EstacionSismologica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoEstacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentoCertificacionAdq")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaSolicitudCertificacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id_Estacion")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitud")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitud")
                        .HasColumnType("REAL");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("NroCertificacionAdquisicion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Estaciones");
                });

            modelBuilder.Entity("PPAI_Revisiones.Modelos.EventoSismico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AlcanceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClasificacionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHoraDeteccion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<double>("LatitudEpicentro")
                        .HasColumnType("REAL");

                    b.Property<double>("LatitudHipocentro")
                        .HasColumnType("REAL");

                    b.Property<double>("LongitudEpicentro")
                        .HasColumnType("REAL");

                    b.Property<double>("LongitudHipocentro")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("OrigenId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResponsableId")
                        .HasColumnType("TEXT");

                    b.Property<double>("ValorMagnitud")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AlcanceId");

                    b.HasIndex("ClasificacionId");

                    b.HasIndex("OrigenId");

                    b.HasIndex("ResponsableId");

                    b.ToTable("EventosSismicos");
                });

            modelBuilder.Entity("PPAI_Revisiones.Modelos.MuestraSismica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SerieTemporalId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SerieTemporalId");

                    b.ToTable("MuestrasSismicas");
                });

            modelBuilder.Entity("PPAI_Revisiones.Modelos.OrigenDeGeneracion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OrigenesDeGeneracion");
                });

            modelBuilder.Entity("PPAI_Revisiones.Modelos.SerieTemporal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CondicionAlarma")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("EventoSismicoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHoraFinRegistroMuestras")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHoraInicioRegistroMuestras")
                        .HasColumnType("TEXT");

                    b.Property<double>("FrecuenciaMuestreo")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("SismografoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventoSismicoId");

                    b.HasIndex("SismografoId");

                    b.ToTable("SeriesTemporales");
                });

            modelBuilder.Entity("PPAI_Revisiones.Modelos.Sismografo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EstacionSismologicaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentificadorSismografo")
                        .HasColumnType("TEXT");

                    b.Property<string>("NroSerie")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EstacionSismologicaId");

                    b.ToTable("Sismografos");
                });

            modelBuilder.Entity("PPAI_Revisiones.Modelos.TipoDeDato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Denominacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUnidadMedida")
                        .HasColumnType("TEXT");

                    b.Property<double>("ValorUmbral")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("TiposDeDato");
                });

            modelBuilder.Entity("PPAI_Revisiones.Modelos.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contraseña")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PPAI_Revisiones.Modelos.CambioDeEstado", b =>
                {
                    b.HasOne("PPAI_Revisiones.Modelos.EventoSismico", null)
                        .WithMany("CambiosDeEstado")
                        .HasForeignKey("EventoSismicoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PPAI_Revisiones.Modelos.Empleado", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("PPAI_Revisiones.Modelos.DetalleMuestra", b =>
                {
                    b.HasOne("PPAI_Revisiones.Modelos.MuestraSismica", null)
                        .WithMany("Detalles")
                        .HasForeignKey("MuestraSismicaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PPAI_Revisiones.Modelos.TipoDeDato", "TipoDeDato")
                        .WithMany()
                        .HasForeignKey("TipoDeDatoId");

                    b.Navigation("TipoDeDato");
                });

            modelBuilder.Entity("PPAI_Revisiones.Modelos.Empleado", b =>
                {
                    b.HasOne("PPAI_Revisiones.Modelos.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("PPAI_Revisiones.Modelos.Empleado", "UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PPAI_Revisiones.Modelos.EventoSismico", b =>
                {
                    b.HasOne("PPAI_Revisiones.Modelos.AlcanceSismo", "Alcance")
                        .WithMany()
                        .HasForeignKey("AlcanceId");

                    b.HasOne("PPAI_Revisiones.Modelos.ClasificacionSismo", "Clasificacion")
                        .WithMany()
                        .HasForeignKey("ClasificacionId");

                    b.HasOne("PPAI_Revisiones.Modelos.OrigenDeGeneracion", "Origen")
                        .WithMany()
                        .HasForeignKey("OrigenId");

                    b.HasOne("PPAI_Revisiones.Modelos.Empleado", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableId");

                    b.Navigation("Alcance");

                    b.Navigation("Clasificacion");

                    b.Navigation("Origen");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("PPAI_Revisiones.Modelos.MuestraSismica", b =>
                {
                    b.HasOne("PPAI_Revisiones.Modelos.SerieTemporal", null)
                        .WithMany("Muestras")
                        .HasForeignKey("SerieTemporalId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PPAI_Revisiones.Modelos.SerieTemporal", b =>
                {
                    b.HasOne("PPAI_Revisiones.Modelos.EventoSismico", null)
                        .WithMany("SeriesTemporales")
                        .HasForeignKey("EventoSismicoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PPAI_Revisiones.Modelos.Sismografo", "Sismografo")
                        .WithMany()
                        .HasForeignKey("SismografoId");

                    b.Navigation("Sismografo");
                });

            modelBuilder.Entity("PPAI_Revisiones.Modelos.Sismografo", b =>
                {
                    b.HasOne("PPAI_Revisiones.Modelos.EstacionSismologica", "Estacion")
                        .WithMany()
                        .HasForeignKey("EstacionSismologicaId");

                    b.Navigation("Estacion");
                });

            modelBuilder.Entity("PPAI_Revisiones.Modelos.EventoSismico", b =>
                {
                    b.Navigation("CambiosDeEstado");

                    b.Navigation("SeriesTemporales");
                });

            modelBuilder.Entity("PPAI_Revisiones.Modelos.MuestraSismica", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("PPAI_Revisiones.Modelos.SerieTemporal", b =>
                {
                    b.Navigation("Muestras");
                });
#pragma warning restore 612, 618
        }
    }
}
